### ISSUE TITLE
Error: invalid cmd_out returned.

### ISSUE THREAD

**Issue by kierancrown** [mrchimp/cmd#6] opened 2016-07-27 12:53 UTC
Not sure why I'm getting this, I'm passing an object with both cmd_in & cmd_out values to the handleRequest method but keep getting 'Error: invalid cmd_out returned.' printed out on the screen.

**Comment by mrchimp** [comment] 2016-07-27 13:07
Hi Kieran. Don't have time to look into it properly right now but this might be related to the 1.1.0 update where I made some changes to the format of the response and probably didn't document it properly.

Checkout [this class](https://github.com/mrchimp/chimpcom/blob/master/app/Mrchimp/Chimpcom/Response.php) for some working PHP code. The `$out` variable should be the structure you're looking for. If you're still having problems, post your object here and i'll take a look at it.

**Comment by mrchimp** [comment] 2016-08-02 11:36
Did you ever get to the bottom of this?

**Comment by mrchimp** [comment] 2016-08-20 13:51
As far as I can tell this is working as intended. You will get this error if cmd_out is not a string. Maybe you're returning an integer or something instead? I'm closing this for now but if you think there is a legit bug then let me know.

**Closed by mrchimp** 2016-08-20 13:51 UTC
